name: Main build workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - '.gitignore'

jobs:
  build:
    name: Build
    runs-on: latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - name: Build target
        run: npm run build
